_target_: animatableGaussian.deformer.mm_model.SMPLModel
model_path: ../../data/smpl
num_players: ${dataset.num_players}
gender: ${dataset.gender}
num_repeat: 1
max_sh_degree: ${max_sh_degree}
max_freq: ${max_freq}
use_point_color: ${use_point_color}
use_point_displacement: ${use_point_displacement}
