_target_: animatableGaussian.dataset.mmdataset.MMPeopleSnapshotDataModule
name: male-4-casual
num_workers: ${num_workers}
gender: male
subject: male-4-casual
num_players: 1
opt:
  dataroot: ../../data/people_snapshot/${dataset.subject}
  max_freq: ${max_freq}
  camera:
    focal_length_x: 2664.22975
    focal_length_y: 2664.69277
    camera_center_x: 511.780554
    camera_center_y: 567.125429
    width: 1080
    height: 1080
  train:
    start: 0
    end: 659
    skip: 24 #108 # 54
    skip_pose_base: 6
    downscale: 2
  val:
    start: 659
    end: 659
    skip: 6
    downscale: 2
  test:
    start: 660
    end: 872
    skip: 6
    downscale: 2